version: "3"
services:
  cache:
    image: redis
    container_name: starter-cache
    ports:
      - "6379:6379"
    networks:
      - backend

  database:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: starter-db
    ports:
      - "3306:3306"
    networks:
      - backend
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=starter
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=starter
      - MYSQL_PASSWORD=secret

  api:
    build:
      context: ../
      dockerfile: ./artifacts/Dockerfile
    image: starter-api
    container_name: starter-api
    ports:
      - "8080:8080"
    networks:
      - backend
      - frontend

networks:
  backend:
  frontend:
